# Generated by Django 3.1.2 on 2026-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20260119_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
