# Generated by Django 3.1.2 on 2026-01-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_seat_seatreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagaMilesAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=20)),
                ('miles_awarded', models.IntegerField()),
                ('original_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('status', models.CharField(choices=[('AWARDED', 'Awarded'), ('REVERSED', 'Reversed')], default='AWARDED', max_length=15)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SagaPaymentAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(max_length=50)),
                ('authorization_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('flight_fare', models.FloatField()),
                ('other_charges', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='AUTHORIZED', max_length=15)),
                ('payment_method', models.CharField(default='mock_card', max_length=20)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SagaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(max_length=50, unique=True)),
                ('booking_data', models.JSONField()),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('COMPENSATED', 'Compensated')], default='STARTED', max_length=15)),
                ('steps_completed', models.IntegerField(default=0)),
                ('failed_step', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('compensation_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
