# Generated by Django 3.1.2 on 2026-01-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_auto_20260123_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagaLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(db_index=True, max_length=50)),
                ('step_name', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('log_level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('compensation', 'Compensation')], default='info', max_length=15)),
                ('message', models.TextField()),
                ('is_compensation', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sagalogentry',
            index=models.Index(fields=['correlation_id', 'timestamp'], name='flight_saga_correla_167351_idx'),
        ),
    ]
