# Generated by Django 3.1.2 on 2026-01-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('tier_status', models.CharField(default='Regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SagaMilesAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(max_length=50)),
                ('miles_awarded', models.IntegerField()),
                ('original_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
                ('status', models.CharField(choices=[('AWARDED', 'Awarded'), ('REVERSED', 'Reversed')], default='AWARDED', max_length=15)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saga_awards', to='loyalty.loyaltyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('flight_booking', 'Flight Booking'), ('miles_redemption', 'Miles Redemption'), ('bonus_award', 'Bonus Award'), ('adjustment', 'Adjustment')], max_length=20)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('points_value', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
